### ISSUE TITLE
fetch_mpa error

### ISSUE THREAD

**Issue by jevanilla** [BigelowLab/mpatools#3]
Error in checkError(res) : 
  Undefined error in httr call. httr output: Failed to connect to localhost port 4567: Connection refused 
12.
stop(err) 
11.
checkError(res) 
10.
queryRD(qpath, "POST", qdata = serverOpts) 
9.
rd$open(silent = TRUE) 
8.
tryCatchList(expr, classes, parentenv, handlers) 
7.
tryCatch({
    url <- character(0)
    pjs <- wdman::phantomjs(verbose = FALSE)
    rd <- RSelenium::remoteDriver(port = 4567L, browserName = "phantomjs") ... 
6.
withCallingHandlers(expr, message = function(c) if (inherits(c, 
    classes)) tryInvokeRestart("muffleMessage")) 
5.
suppressMessages(tryCatch({
    url <- character(0)
    pjs <- wdman::phantomjs(verbose = FALSE)
    rd <- RSelenium::remoteDriver(port = 4567L, browserName = "phantomjs") ... 
4.
try_and_find_url(x) 
3.
wdpa_url(x, wait = wait) 
2.
wdpar::wdpa_fetch(name[1], wait = TRUE, download_dir = tempdir(), 
    ...) at mpa.R#56
1.
fetch_mpa() 

[
](https://github.com/prioritizr/wdpar/issues/7)
[
](https://github.com/prioritizr/wdpar/issues/14)

**Comment by jevanilla** [comment]
https://github.com/prioritizr/wdpar/issues/14

**Comment by btupper** [comment]
Hmmm.  Related to https://github.com/ropensci/wdman/issues/29

**Comment by btupper** [comment]
Will be resolved when wdman updates.
